include classpath("application.conf")

queues {
  payroll-jobs {
    defaultVisibilityTimeout = 600 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }

  payment-results {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
